### PR TITLE
master-qa-26349

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26349

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:restest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41549
https://github.com/brianchandotcom/liferay-portal/pull/41551

**Pull request closed without merging**
