### PR TITLE
master-qa-71211

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-71211
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
@Jayda-4145 Oh wait, we don't need the new macro, as you didn't use it in your test.  So I removed it.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/109678

**Comment by jaydawu** [comment]
@brianwulbern Ok, thanks.

**Pull request closed without merging**
