### PR TITLE
master-rs-31

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-22303

### CODE REVIEW

**Comment by brianwulbern** [comment]
SF for @melodywu @Hanlf @GinsonRen 

I'm sorry you three had to run into this test failure - because it was a poorly written test!  If you look at: (https://github.com/liferay/liferay-plugins/blob/master/portlets/test-dependency-fox-portlet/docroot/WEB-INF/liferay-plugin-package.properties#L10-L12) and (https://github.com/liferay/liferay-plugins/blob/master/portlets/test-dependency-easy-portlet/docroot/WEB-INF/liferay-plugin-package.properties#L10-L12) you'll see that Fox and Easy require each other as deployed plugins, in order for them to display in the Add panel.

That being said, if we want to _test_ this dependency, then we should remove _one_ of them from the list of deployed plugins on the top of the file (in portlet.plugins.includes).  We can also have a test that checks that all the dependencies work when met (that is, that when every one of the test plugins is deployed, then they're all visible and add-able to a page).  This is how your fix changed it.  But since the test is named "_ViewDependencyAbleFox_", we'll want to focus on those dependencies.  So I'm going to remove 'fox' from the deploy list and keep the steps the same as they're written before the test fix.

I made a [ticket](https://issues.liferay.com/browse/LRQA-26115) for us to add more dependency testcase files for the other scenarios.  We can add subtasks to this as we add new tests

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40928
https://github.com/brianchandotcom/liferay-portal/pull/40929

**Comment by brianwulbern** [comment]
CC @alee8888, regarding the linked ticket above

**Comment by melodywu** [comment]
@brianwulbern 
Thank you for your explanation for the test. We have understand your point that if we want to test dependency one of the plugins should be removed.We will watch the ticket for more dependency testcase files.

**Pull request closed without merging**
