### PR TITLE
master-qa-72088

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-32122

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
cc @brianwulbern

**Comment by brianwulbern** [comment]
@HarryC0204 please add the logout, login steps listed on [LRQA-32122](https://issues.liferay.com/browse/LRQA-32122), and resend.  Thanks!

**Comment by brianwulbern** [comment]
ci:stop

**Pull request closed without merging**
