### PR TITLE
master-qa-19457

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-19457

### CODE REVIEW

**Comment by brianwulbern** [comment]
Hi @kmaria 

Is this a P5 test?  Do you want this in the PR tester?

{{<property name="portal.acceptance" value="true" />}}

You can add it later, if so, but for now I'll downgrade it to a P4 (according to your [ticket](https://issues.liferay.com/browse/LRQA-19457)).

**Comment by kmaria** [comment]
Hi @brianwulbern 

P5, yes, and not yet needed in PR tester. Thanks

**Comment by brianwulbern** [comment]
SF for MKispal.

* Removed one unused var in your Page#add call...then found a bunch more around our poshi files (thus all the commits)

**Comment by brianwulbern** [comment]
Pushed to ENagayama.
https://github.com/evannagayama/liferay-portal/pull/552

**Pull request closed without merging**
