### PR TITLE
master-qa-71314

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-71314
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
fyi @suilin this looks good to me, but can you confirm whether this case is tested by any other functional or backend testing in Publications?  Thanks!

**Comment by suilin** [comment]
Hi @brianwulbern, this case actually can be covered by `PublicationsPage#ResolveConflictingPublicationsByDiscarding`. Since LPS-138726 is the expected reulst may I ask why it need to automate? Thank you!

**Comment by brianwulbern** [comment]
@suilin I think _because_ the LPS was closed as Won't Fix, that made the need for the test to be about ensuring that "the content page from Production appears in publication."  But if this case is already covered by `PublicationsPage#ResolveConflictingPublicationsByDiscarding` as you said, I don't think we need to add this test.  Thanks!

**Comment by suilin** [comment]
Got it, thank you @brianwulbern!

**Pull request closed without merging**
