### PR TITLE
master-qa-26443

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26443

@juliocamarero @epgarcia - I've made some test fixes to account for the changes to the rules instances, which will allow our existing tests to run successfully. I've also added 1 new test (`ContentTargetingUserSegment#AddUserSegmentBehaviorCustomFieldCP`) to cover an existing feature that did not yet have a testcase. Finally, I've added 9 new test cases in order to cover the 9 rules that leverage multi-instantiability. Once these new tests are merged, we can run on the the RC using with these new tests as well.

### CODE REVIEW

**Comment by anthony-chu** [comment]
Staging failures due to known issue: [LPS-67055](https://issues.liferay.com/browse/LPS-67065).

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Nice work with the new tests @anthony-chu!

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41432
https://github.com/brianchandotcom/liferay-portal/pull/41435

**Comment by juliocamarero** [comment]
Awesome!! Thank a lot @anthony-chu! 👍

**Pull request closed without merging**
