### PR TITLE
LRQA-35000 Remove old ProductMenu navigation macros

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-35000

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:sf

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:test

**Comment by anthony-chu** [comment]
The `CPRolesCPWebContent` acceptance test failure was not caused by the changes for LRQA-35000.

**Comment by brianwulbern** [comment]
* Fixed the last remaining ones.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64831
https://github.com/brianchandotcom/liferay-portal-ee/pull/22285

**Comment by brianwulbern** [comment]
Thanks @anthony-chu!

**Pull request closed without merging**
