### PR TITLE
master-qa-72088

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-32122

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
cc @brianwulbern

**Comment by brianwulbern** [comment]
note to self

for an alternate search method, search for:
`samlEnabled = "true",`

so we don't need to [add new logic](https://github.com/brianwulbern/liferay-portal/pull/239/files#diff-8a66feb62f28004b91c0b1501e47fc0aR1531)

**Comment by brianwulbern** [comment]
SF for @HarryC0204 

* Combined the localization logic into a reusable form.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66711
https://github.com/brianchandotcom/liferay-portal-ee/pull/22988

**Pull request closed without merging**
