### PR TITLE
master-qa-16107

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-16107

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@kmaria 

Can you fix the rebase error and force push?  Thanks!

**Comment by kmaria** [comment]
@brianwulbern Rebased.

**Comment by kmaria** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for MKispal.

* Fixed the source formatter issue

**Comment by brianwulbern** [comment]
Pushed to ENagayama.
https://github.com/evannagayama/liferay-portal/pull/699

**Pull request closed without merging**
