### PR TITLE
LRQA-49757, LRQA-49766, LRQA-49897 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-49757
https://issues.liferay.com/browse/LRQA-49766
https://issues.liferay.com/browse/LRQA-49897
Can cherry pick to 7.2.x
cc @GinsonRen

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74790
https://github.com/brianchandotcom/liferay-portal-ee/pull/25110

**Pull request closed without merging**
