### PR TITLE
LPS-122403 Append automatic copy

### PR DESCRIPTION
**Pull request by petershin**
Hi @brianwulbern, please check the generated changes in https://github.com/brianwulbern/liferay-portal/pull/285/commits/5e0eb0e12b048b804a09a7e6062c2d6b01793953.  If it looks good, please forward to bchan

### CODE REVIEW

**Comment by brianwulbern** [comment]
Thanks for this, @petershin! Will this automatically be backported all the way to 7.0, or can I cherry-pick it?

**Comment by petershin** [comment]
@brianwulbern - I can send it to bchan.  Can you confirm that the statements below are correct:

1) the `buildLang` task should always use the new logic - i.e. add (Automatic Copy) if its missing
2) the language keys need to be updated on master, 7.3.x, 7.2.x, 7.1.x, 7.0.x

**Comment by brianwulbern** [comment]
@petershin 

Yes, both statements are true.  Although, if it's expensive on RAM, you could put the new logic in a separate task.

When resolving conflicts that showed in this pull, I just always defer to "ours", because any new strings will just show up in the next buildLang.  Since this makes a bunch of changes to files, you'll probably hit conflicts in your backport pulls.  You can send to me to resolve them if you don't have time to deal with it.

**Comment by brianwulbern** [comment]
Rebased and resent to https://github.com/brianwulbern/liferay-portal/pull/286 to forward

**Pull request closed without merging**
