### PR TITLE
LRQA-38144 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-38144

7.0.x: https://github.com/brianwulbern/liferay-portal-ee/pull/512

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:test

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/19410

**Comment by brianwulbern** [comment]
Pushed to AChu.
https://github.com/anthony-chu/liferay-portal/pull/359

**Pull request closed without merging**
