### PR TITLE
master-qa-54757

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-54757

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to CMagalhaes.
https://github.com/cvanut/liferay-portal/pull/9
https://github.com/cvanut/liferay-portal-ee/pull/4

**Pull request closed without merging**
