### PR TITLE
master-qa-72584

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-72584
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@JoyceWang08211 let me know if you'd like to change anything with this test, otherwise I'll forward it.

7.3 https://github.com/brianwulbern/liferay-portal-ee/pull/1148
7.2 https://github.com/brianwulbern/liferay-portal-ee/pull/1149

**Comment by JoyceWang08211** [comment]
I think the testcase need to be moved into ExportImport.testcase rather than SiteExportImport.testcase.
ExportImport.testcase belongs to Staging team.
SiteExportImport.testcase belongs to echo team.

cc @brianwulbern @chaowang-123

**Comment by brianwulbern** [comment]
@chaowang-123 can you go ahead and move the test over to ExportImport.testcase and resend for 7.3 and 7.2?  I'll take care of master.  Thanks!

**Comment by chaowang-123** [comment]
> ExportImport.testcase belongs to Staging team.
> SiteExportImport.testcase belongs to echo team.

Ok, I will.

**Comment by brianwulbern** [comment]
Moved on master in
https://github.com/brianwulbern/liferay-portal/pull/407

**Comment by brianwulbern** [comment]
Thanks, @JoyceWang08211 !

**Pull request closed without merging**
