### PR TITLE
master-rs-22

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-28028

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:stop

**Comment by GinsonRen** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44090
https://github.com/brianchandotcom/liferay-portal/pull/44096

**Pull request closed without merging**
