### PR TITLE
LPS-186127 Move allowedSingleWordLanguageKeys to txt file

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @brianwulbern 
I think `allowed-single-word-language-keys.txt` is a better file name.

1. add more keys in txt
2. go to `modules/util/source-formatter`, run `../../../gradlew deploy`
4. in `portal-impl`, run `ant format-source`

/cc @qz1010

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
Added keys and sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/139065

**Pull request closed without merging**
