### PR TITLE
master-qa-29905

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-29905

### CODE REVIEW

**Comment by liuxingye** [comment]
@GinsonRen

**Comment by brianwulbern** [comment]
SF for @liuxingye 

* Shortened the locator name to be simpler.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45964
https://github.com/brianchandotcom/liferay-portal/pull/45968

**Comment by liuxingye** [comment]
@brianwulbern Got it, thanks.

**Pull request closed without merging**
