### PR TITLE
master-qa-22296

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-22296

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for MKispal.

* Added a navigation step, and did some line-spacing SF

**Comment by brianwulbern** [comment]
Pushed to ENagayama.
https://github.com/evannagayama/liferay-portal/pull/693

**Pull request closed without merging**
