### PR TITLE
master-qa-40457

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-40457
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@chaowang-123 good job with the test name here!  Clear and descriptive.

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
master https://github.com/brianchandotcom/liferay-portal-ee/pull/35968
7.3.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35968
7.2.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35974
7.1.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35975

**Pull request closed without merging**
