### PR TITLE
7.0.x-qa-28966

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-28966

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44682
https://github.com/brianchandotcom/liferay-portal/pull/44683

**Pull request closed without merging**
