### PR TITLE
master-qa-14592

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-14592

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@kmaria I'll go ahead and push this through, but keep in mind, we want to group code logic in commits based on the logic, not the test files.  See https://in.liferay.com/web/global.engineering/wiki/-/wiki/Quality+Assurance+Main/Automation+Test+Commit+Standards

**Comment by brianwulbern** [comment]
@kmaria 

Does the test pass beyond the Staging#configurePublishToLive block [here](https://github.com/brianwulbern/liferay-portal/pull/134/commits/bd66ab8cf25baefbef9f11f7a67acbee6172afe3#diff-8fa0b0752fa4015823b463e7382b6b5bR4080)?  Your index only goes that far?

**Comment by kmaria** [comment]
@brianwulbern Checked it, test is passing for me. Btw, have rebased to master.

**Comment by brianwulbern** [comment]
SF for MKispal.

* Added some spaces where the order of the steps is not interchangeable.

**Comment by brianwulbern** [comment]
Pushed to ENagayama.
https://github.com/evannagayama/liferay-portal/pull/698

**Pull request closed without merging**
