### PR TITLE
master-qa-27301

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-27301

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:retest

**Comment by GinsonRen** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for @GinsonRen 
- Fixed a commit message typo
- Combined steps from the testcase into existing macros, so we can avoid the CKEditor/AlloyEditor difference
- Renamed the test to be clearer about its purpose (ReplyAfterDownloadingMBThreadAttachmentTwice), since the purpose is about Reply functionality _after_ downloading
- Streamlined the vars across the testcase file

**Comment by brianwulbern** [comment]
Pushed to SChoi.
https://github.com/sharonchoi/liferay-portal/pull/861
https://github.com/sharonchoi/liferay-portal/pull/862

**Pull request closed without merging**
