### PR TITLE
master-qa-71325

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-71325
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
```  [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase expected:<...rt(123)</script>");
     [java] []
     [java] 		AssertAlertNotPre...> but was:<...rt(123)</script>");
     [java] [		]
     [java] 		AssertAlertNotPre...>
     [java] ```

@Jayda-4145 can you fix the SF and resend?

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
Pushed master to BChan
https://github.com/brianchandotcom/liferay-portal/pull/109362

**Pull request closed without merging**
