### PR TITLE
LRQA-30681, LRQA-30791 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-30681
https://issues.liferay.com/browse/LRQA-30791

### CODE REVIEW

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
@Hanlf @GinsonRen 

The proper grammar for the commit message is:

"Add pause to make sure publish process _is_ finished"

You could also use "..._has_ finished" that's a close second place.

**Comment by Hanlf** [comment]
@brianwulbern 
Thanks for your explain.

**Comment by brianwulbern** [comment]
Pushed ba841d3 to SChoi.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/47039
https://github.com/brianchandotcom/liferay-portal/pull/47041

**Pull request closed without merging**
