### PR TITLE
master-qa-39706

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-39706
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@chaowang-123 is the template engine using Freemarker by default?  Is that why you didn't need to specify the name during the test?

**Comment by chaowang-123** [comment]
yes, template engine using Freemarker by default

**Comment by brianwulbern** [comment]
No test changes needed :)

Good job naming the test, @chaowang-123!

**Comment by brianwulbern** [comment]
Pushed to BChan.
master https://github.com/brianwulbern/liferay-portal/pull/349
7.3 https://github.com/brianchandotcom/liferay-portal-ee/pull/35857

**Pull request closed without merging**
