### PR TITLE
master-qa-26024

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26024

cc @juliocamarero @epgarcia These are new test cases for [WCM-366](https://issues.liferay.com/browse/WCM-366). One applies the "Starts with" condition, and the other applies the "Contains" condition. I have plans to add a third test to assert that both can be used together, but Poshi currently does not have the functionality to do so. I'll add that test case in once Poshi can handle new functionality.

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by epgarcia** [comment]
Thanks @anthony-chu!

**Comment by brianwulbern** [comment]
SF for AChu.

* Ran into an extra line at the end of the new tests, fixed in an Auto SF.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41063
https://github.com/brianchandotcom/liferay-portal/pull/41064

**Comment by juliocamarero** [comment]
👍 good job!

**Pull request closed without merging**
