### PR TITLE
[TS] LPS-136014 Change organization to organisation for british spelling

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @brianwulbern,
I changed organization to organisation in portal-impl for en_GB due to a customer request.
I wanted to update the strings on Crowdin, but looks like en_GB repository does not exist or not available there, so I chose to push the changes here to liferay-portal. Hope that it is still a correct way to do it, but let me know if not.
Please find more information: [LPS-136014](https://issues.liferay.com/browse/LPS-136014)

Could you please review it?
Thanks!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
Sent with some more changes to: https://github.com/brianwulbern/liferay-portal/pull/307

**Comment by brianwulbern** [comment]
I realized (after sending 307) that we can also do "behavior" --> "behaviour" which is the most common word from [this list](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#-our,_-or) in our files

**Comment by brianwulbern** [comment]
But I want to see if we can add the locales into Crowdin first before manually updating more lines.

**Pull request closed without merging**
