### PR TITLE
master-qa-34129

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-34129

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
cc @brianwulbern

**Comment by brianwulbern** [comment]
SF for @SylviaLuan 

* Moved `scopeSite` conditional into existing code and removed duplicate from WebContent.macro.
* Updated commit message

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66614
https://github.com/brianchandotcom/liferay-portal-ee/pull/22957

**Pull request closed without merging**
