### PR TITLE
LRQA-73312 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LRQA-73312

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@WYZ-Issac this looks good!  Please revise your pull on 7.3 and resend that https://github.com/brianwulbern/liferay-portal-ee/pull/1151

**Comment by brianwulbern** [comment]
ci:forward

**Pull request closed without merging**
