### PR TITLE
master-qa-41521

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-41521
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@chaowang-123 I would change the test name to: `GuestUserCanNotSeeFormAfterPermissionRemoved`

Otherwise no test changes needed :)

Can you send this to 7.3.x as well?  Thanks.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/107642
https://github.com/brianchandotcom/liferay-portal-ee/pull/35464
https://github.com/brianchandotcom/liferay-portal-ee/pull/35466
https://github.com/brianchandotcom/liferay-portal-ee/pull/35473

**Pull request closed without merging**
