### PR TITLE
master-qa-72489

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-72489
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@chaowang-123 this was a difficult test to name, and I think you did a good job with it - nice work!  Test looks good too.

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
ci:forward

**Comment by chaowang-123** [comment]
> @chaowang-123 this was a difficult test to name, and I think you did a good job with it - nice work! Test looks good too.

oh, thank you!

**Pull request closed without merging**
