### PR TITLE
master-qa-35622

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-35622
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

Waiting for @Jayda-4145 to send backports

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/107884
https://github.com/brianchandotcom/liferay-portal-ee/pull/35502
https://github.com/brianchandotcom/liferay-portal-ee/pull/35503
https://github.com/brianchandotcom/liferay-portal-ee/pull/35504
https://github.com/brianchandotcom/liferay-portal-ee/pull/35505

**Pull request closed without merging**
