### PR TITLE
master-rs-39

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-23868

### CODE REVIEW

**Comment by brianwulbern** [comment]
@alee8888 Can you give these commits a look over?  There are quite a few changes, so I just want another set of eyes.  Thanks!

**Comment by alee8888** [comment]
@brianwulbern Looks good! Please go ahead and send.

**Comment by brianwulbern** [comment]
:+1:

**Comment by brianwulbern** [comment]
@Sharryxue Nice work, that was a lot of changes!

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41673
https://github.com/brianchandotcom/liferay-portal/pull/41674

**Pull request closed without merging**
