### PR TITLE
master-qa-26606

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26606

### CODE REVIEW

**Comment by anthony-chu** [comment]
Sybase upgrade failure unrelated to the commits in this pull request.

**Comment by brianwulbern** [comment]
@anthony-chu Do we need the PREVIOUS_STATUS locator now?

**Comment by anthony-chu** [comment]
No, we don't need it now, but I added it in as well to make it available, since I already added CURRENT_STATUS

**Comment by brianwulbern** [comment]
Ok, that's what I thought.  As long as you'll add new tests with it soon.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41594
https://github.com/brianchandotcom/liferay-portal/pull/41596

**Pull request closed without merging**
