### PR TITLE
master-qa-43072

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-43072
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

@Jayda-4145 nice job!

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/107642
https://github.com/brianchandotcom/liferay-portal-ee/pull/35464
https://github.com/brianchandotcom/liferay-portal-ee/pull/35466
https://github.com/brianchandotcom/liferay-portal-ee/pull/35473

**Pull request closed without merging**
