### PR TITLE
master-qa-21556

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-21556
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/107884
https://github.com/brianchandotcom/liferay-portal-ee/pull/35502
https://github.com/brianchandotcom/liferay-portal-ee/pull/35503
https://github.com/brianchandotcom/liferay-portal-ee/pull/35504
https://github.com/brianchandotcom/liferay-portal-ee/pull/35505

**Pull request closed without merging**
