### PR TITLE
master-qa-18314

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-18314

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
Review for JPince.

1. The test naming pattern is to capitalize each word (upper camel case), unlike the macro command naming standard (lower camel case) cf. (https://en.wikipedia.org/wiki/CamelCase)
2. You'll want the login step up in the <set-up> block, instead of [here](https://github.com/jpince/liferay-portal/commit/fedd5e08599809a5d9bb6bd0ee619b6f636edaa7#diff-d4327aacd6425594476fd317e2754f91R5) - yeah, ant format-source just [failed](https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/14113/testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/)
3.  Dont need to pass in key variables from the testcase level, so this [line](https://github.com/jpince/liferay-portal/commit/fedd5e08599809a5d9bb6bd0ee619b6f636edaa7#diff-d4327aacd6425594476fd317e2754f91R22) is unnecessary: 
4.  You can probably put this in an existing testcase file, instead of WebcontentOrderByHeading.testcase
5. Add [Line space](https://github.com/jpince/liferay-portal/commit/21c8d8185ca38caf25574ee2e615f2fb4e8642b9#diff-916bf38552857128fb55627d36c927f1R1650) between key var and commands.
6. Can you think of a final assertion this test might use that would be helpful for checking functionality?

**Comment by jpince** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@jpince 

This [line](https://github.com/jpince/liferay-portal/commit/bab7fbb2c85f4188bdc4ab92a268647e62aa1e7e#diff-b28fd4b49da581e6d4374de8bd89ecdcR1137) is probably what's causing the source formatter to fail.

**Comment by jpince** [comment]
ci: retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
huzzah!

Jason Pince
Liferay QA

**Comment by brianwulbern** [comment]
Good job fixing up the things I requested!

Remember to keep in mind 'pushing the quality forward' and testing the next logical step(s) coming after the bug fix point.  Closing this pull for the next trainee to have a crack at writing a test for it. :)

**Pull request closed without merging**
