### PR TITLE
Master-qa-72131

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-72131

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
cc. @yunlinsun

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
ci:forward

**Pull request closed without merging**
