### PR TITLE
LRQA-73103 | master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LRQA-73103

The test is blocked and waiting on [POSHI-256](https://issues.liferay.com/browse/POSHI-256)

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
Hey @WYZ-Issac,

I'm looking to streamline `addGeolocationCP` to only what we need on that.  Do we need to set all the User email, first, last and screen names [here](https://github.com/brianwulbern/liferay-portal/pull/404/commits/d3b7d3011d073ca5509312bf614487117020313f#diff-f09d91ccec482edf98bd5989a7cee62ccb423d8ff4faefec8ee2650b40933e11R283-R287)?  Are they all necessary?

**Comment by brianwulbern** [comment]
It looks like you copied User.addCP directly, am I right?

**Comment by WYZ-Issac** [comment]
@brianwulbern Yes, I copied most of it and insert the draganddrop function in the addGeolocationCP macro, but the function can not let the case pass. So I delete the it to make the test pass. Is it OK?

**Comment by WYZ-Issac** [comment]
If  we don't set all the User email, first, last and screen names. The user can not add as normal. These settings are all required.

**Comment by brianwulbern** [comment]
@WYZ-Issac ok, use the normal user adding macro `User.addCP` to add, then try to pass in the draganddrop function in, either after or during new user creation.  You can comment before the draganddrop function that it's broken (`//`) (press `Ctrl` + `?` in Sublime)

Example:
"// This test is being ignored due to a history that makes changes to empty state messages."

You can add the comment right before the part of the test that is failing and waiting for POSHI-256

**Comment by brianwulbern** [comment]
@WYZ-Issac see the changes I made in https://github.com/brianwulbern/liferay-portal/pull/411

I cherry-picked in some of @Tim-Cao 's commits to make it work, rearranged the macros so it's only done when the variable is set, so it's not a lot of duplicate functionality, then we can turn the test on after POSHI-256

https://github.com/brianchandotcom/liferay-portal/pull/114839/commits/a662c7f37521c04257f7e6231a0e8582393e6c57
https://github.com/brianchandotcom/liferay-portal/pull/114839/commits/94acd9ba0db39ff26bb5bfb9e6ea2f3e05a98f46

**Pull request closed without merging**
