### PR TITLE
master-qa-19264

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-19264

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@jpince 

[this](https://github.com/jpince/liferay-portal/commit/05caae9ef5c0b325cc2597ba6d8353d96c9d8b54#diff-4f1ab693f1c6a5f0d8c0009a0747584dR330) line through 333 are the problematic ones - can you see how to fix them?

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for JPince.

* I ran into a key var issue when going through another test linked with "LRQA_19264", so I fixed that, otherwise the pull looks good :)

**Comment by brianwulbern** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/983

**Pull request closed without merging**
