### PR TITLE
LPS-63004 SF

### PR DESCRIPTION
**Pull request by jkappler**
@brianwulbern: fixed a NPE. With this one site creation should work.

CC:/ @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
@brianwulbern, as mentioned in the other PR (and doing copy and paste here):

We made some changes to some navigations in Site Admin, and that's why the tests are failing.

Some changes that where made:

- Column with site name has a link to child sites view if it can have children. Before, the user navigated to edit site

- Edit site was moved to actions list, as the first element
 
- There was an issue where, if the user created a site in child sites view, the site was created at top level. This is now fixed in this PR

Just let us know if you need any more info, and we'll be happy to help out.

Thanks for the time

**Comment by evannagayama** [comment]
re: https://github.com/evannagayama/liferay-portal/pull/526

**Comment by ealonso** [comment]
Hey @brianwulbern,

Do you have any update about his pull?

Please let us know, if we can help you with anything.

Regards,
Eudaldo.

**Comment by brianwulbern** [comment]
Hi @jkappler @ealonso 

I'm starting it up now.  It looks like there's an issue with our portal instances listed in the Sites.  I'll let you know asap.

**Comment by brianwulbern** [comment]
Pushed fixes here: https://github.com/evannagayama/liferay-portal/pull/548

Ran a few of the failing tests locally.  Should be good :)

**Pull request closed without merging**
