### PR TITLE
master-qa-71222_2

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-71222
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@chaowang-123 great job fixing this test up!

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
7.0.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/35842
7.1.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/35841
7.2.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/35840
7.3.x - https://github.com/brianchandotcom/liferay-portal-ee/pull/35839
master - https://github.com/brianchandotcom/liferay-portal/pull/109697

**Pull request closed without merging**
