### PR TITLE
master-lps-136621_1

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-136621
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/109277
https://github.com/brianchandotcom/liferay-portal-ee/pull/35770
https://github.com/brianchandotcom/liferay-portal-ee/pull/35771

**Pull request closed without merging**
