### PR TITLE
LRQA-30533, LRQA-305010, LRQA-30504 | 7.0.x 

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-30533
https://issues.liferay.com/browse/LRQA-30501
https://issues.liferay.com/browse/LRQA-30504

### CODE REVIEW

**Comment by brianwulbern** [comment]
@GinsonRen there's a SF error in one of these commits, saying there's an issue with "...knowledgebase/pgknowledgebasedisplay/PGKnowledgebasedisplay.testcase"

Did you see the source-format failure message above?

https://github.com/brianwulbern/liferay-portal/pull/179/commits/6ff8a95a214f8543050e7b95049b5cd8ec76a2d3

**Comment by brianwulbern** [comment]
Pushed 30501 to ALee.
https://github.com/alee8888/liferay-portal/pull/443

**Comment by GinsonRen** [comment]
@brianwulbern Sorry for that, I didn't notice it. I will pay more attention.

**Comment by brianwulbern** [comment]
Pushed 30504 to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/46826
https://github.com/brianchandotcom/liferay-portal/pull/46827

**Pull request closed without merging**
