### PR TITLE
LRQA-51488 Rein in some

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-51488

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
fyi @austinchiang

The following tests have each failed their last 9 runs [(commit range)](https://github.com/liferay/liferay-portal-ee/compare/97a56122c7ed1088374629839287dfec16038de1...0d1d3811dda430bc93e4c3066c796c1c07308e4f):
[KnowledgeBaseArticleResourceTest#testGraphQLGetKnowledgeBaseArticle](https://testray.liferay.com/home/-/testray/cases/863872441)
[KnowledgeBaseArticleResourceTest#testGraphQLGetSiteKnowledgeBaseArticlesPage](https://testray.liferay.com/home/-/testray/cases/863882160)
[KnowledgeBaseArticleResourceTest#testGraphQLDeleteKnowledgeBaseArticle](https://testray.liferay.com/home/-/testray/cases/863875106)
[BlogPostingResourceTest#testGraphQLGetBlogPosting](https://testray.liferay.com/home/-/testray/cases/863870336)
[BlogPostingResourceTest#testGraphQLGetSiteBlogPostingsPage](https://testray.liferay.com/home/-/testray/cases/863877878)
[BlogPostingResourceTest#testGraphQLDeleteBlogPosting](https://testray.liferay.com/home/-/testray/cases/863869011)

**Comment by brianwulbern** [comment]
ci:forward

**Comment by brianwulbern** [comment]
ci:stop

**Comment by Hanlf** [comment]
Filed https://issues.liferay.com/browse/LPS-111125 and post it in the Lima team.

**Comment by austinchiang** [comment]
@brianwulbern @Hanlf  GraphQL tests belong to the headless team. Looks like the fixed has been merged [here](https://github.com/brianchandotcom/liferay-portal/pull/86985).

**Comment by brianwulbern** [comment]
ci:forward

**Pull request closed without merging**
