### PR TITLE
master-qa-37826

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-37826
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
Review changes for @chaowang-123 
* Updating test name to `ValidateRCEReturnsNoRuntimeClasses`
* Asserting `java.lang.Runtime` text is not present

**Comment by brianwulbern** [comment]
Pushed to BChan.
master https://github.com/brianwulbern/liferay-portal/pull/349
7.3 https://github.com/brianchandotcom/liferay-portal-ee/pull/35857
7.2 https://github.com/brianchandotcom/liferay-portal-ee/pull/35858
7.1 https://github.com/brianchandotcom/liferay-portal-ee/pull/35859
7.0 https://github.com/brianchandotcom/liferay-portal-ee/pull/35860

**Pull request closed without merging**
