### PR TITLE
master-qa-26454

### PR DESCRIPTION
**Pull request by vicnate5**
Hey Brian, these are some updates I made to the Content Targeting test for the Forms implementation. I found the test did not run on FF45 and this makes it compatabile. cc @anthony-chu

### CODE REVIEW

**Comment by brianwulbern** [comment]
@vicnate5 @anthony-chu any idea why those ExportImport tests are running the `<tear-down>` block?

**Comment by vicnate5** [comment]
I think @kenjiheigel was working on that test failure.

**Comment by brianwulbern** [comment]
SF for VWare.

* Auto SF

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41327

**Pull request closed without merging**
