### PR TITLE
LRQA-33822 | master

### PR DESCRIPTION
**Pull request by christianstokes**
https://issues.liferay.com/browse/LRQA-33844

### CODE REVIEW

**Comment by christianstokes** [comment]
@brianwulbern:
This PR (and the one for ee-7.0.x) is for a test fix submitted by our QA interns in training. I was told you would be able to review this test. Please let me know if you have any questions.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@christianstokes cool, I'll take a look at it.  There seems to be a big spike in DDL tests on this pull, I'm retesting and analyzing to determine whether the failures are flaky.  Thanks!

**Comment by brianwulbern** [comment]
Ohh, Victor sent a fix for this...

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
Pushed to AChu.
https://github.com/anthony-chu/liferay-portal/pull/176

**Pull request closed without merging**
