### PR TITLE
LRQA-36981 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-36981

### CODE REVIEW

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
SF for @GinsonRen

* Remember to run SF

**Comment by brianwulbern** [comment]
Pushed to AChu.
https://github.com/anthony-chu/liferay-portal/pull/304

**Comment by GinsonRen** [comment]
@brianwulbern sorry for that. Thanks.

**Pull request closed without merging**
