### PR TITLE
master-qa-38221

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-38221

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/66778
https://github.com/brianchandotcom/liferay-portal-ee/pull/23007
https://github.com/brianchandotcom/liferay-portal-ee/pull/23010

**Pull request closed without merging**
