### PR TITLE
master-qa-26106

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26106

cc @juliocamarero @epgarcia These are test fixes and a new test for [WCM-591](https://issues.liferay.com/browse/WCM-591). I've renamed our original test from `ContentTargetingCampaign#AddCampaignFormCP` to `ContentTargetingCampaign#AddCampaignCustomFormCP`; I've also added a new test `ContentTargetingCampaign#AddCampaignDDLFormCP`.

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for AChu.

* Ran into an extra line at the end of the new tests, fixed in an Auto SF.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41063
https://github.com/brianchandotcom/liferay-portal/pull/41064

**Comment by juliocamarero** [comment]
Awesome! 👍

**Pull request closed without merging**
