### PR TITLE
master-qa-18314

### PR DESCRIPTION
**Pull request by christieyoo**
https://issues.liferay.com/browse/LRQA-18314

### CODE REVIEW

**Comment by brianwulbern** [comment]
@christieyoo 
Good job!  Will look more at this one after other test fixes.

**Comment by brianwulbern** [comment]
Review for CYoo.

@christieyoo 
* Good job with this test!
* Why did you remove the locators here: (https://github.com/christieyoo/liferay-portal/commit/34f8621af7ea77ec7e1f30d3bc91ec5101e140f7)?
* Something you might try is to Edit the WC article, to see whether having >1 version will influence the error outcome when sorting by version.
* What's another step you might add to ensure the quality of sorting by version?

**Comment by christieyoo** [comment]
Regarding those locators that were removed -- they weren't in my source file, but appeared in SmartGit when I was committing my changes.  Not sure what happened there.

**Comment by brianwulbern** [comment]
Oh, you're right.  It reorganized them in as confusing a way as possible.  They just went to the bottom after they got sorted.

**Pull request closed without merging**
