### PR TITLE
master-qa-45951_1

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-45951
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
Pushed to BChan where applicable on
master https://github.com/brianchandotcom/liferay-portal/pull/110040
7.3.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35908
7.2.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35909
7.1.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35906
7.0.x https://github.com/brianchandotcom/liferay-portal-ee/pull/35907

**Pull request closed without merging**
