### PR TITLE
master-qa-71211

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-71211
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@Jayda-4145 is there not an "All" option like the [bug ticket](https://issues.liferay.com/browse/LPS-139477) describes?

**Comment by jaydawu** [comment]
@brianwulbern I asked Melody for this. She said that the default "Active" represents the "All" option, but she needs to ask her lead patty if we need to add a guest test. We might get a reply tomorrow as soon as possible.

**Comment by brianwulbern** [comment]
Ok, thanks @Jayda-4145 - I'll await your reply :)

**Comment by patriciajeanperez** [comment]
Hi @brianwulbern and @Jayda-4145, "Active" status and "Guest" accounts are two different filters. "Active" is an account status, while "Guest" is an account type. This test is meant to cover filtering by type and not status so I wouldn't associate filtering by Active with this test. 

@melodywu I think we can just update `Accounts#CanFilterAccountsByType` to include Guest accounts

**Comment by patriciajeanperez** [comment]
@brianwulbern @Jayda-4145 oh, "All" filter was removed as part of [LPS-138696.](https://issues.liferay.com/browse/LPS-138696). So "All" would be not filtering by a specific type.

**Comment by jaydawu** [comment]
Thanks for your reply! @patriciajeanperez 
cc @brianwulbern

**Pull request closed without merging**
