### PR TITLE
master-rs-14

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-23043

### CODE REVIEW

**Comment by brianwulbern** [comment]
SF for @liuxingye @GinsonRen 

* I updated the commit message to be "Navigate to Site Admin portlet", the commit is good :)

**Comment by liuxingye** [comment]
@brianwulbern 
Got it. Thanks.

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40761

**Comment by liuxingye** [comment]
@brianwulbern 
Got it. Thanks.

**Pull request closed without merging**
