### PR TITLE
master-qa-26573

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26573

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest for stability

**Comment by anthony-chu** [comment]
Test has passed two PR tester runs without failing.

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41549
https://github.com/brianchandotcom/liferay-portal/pull/41551

**Pull request closed without merging**
