### PR TITLE
master-qa-17595

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-17595

### CODE REVIEW

**Comment by brianwulbern** [comment]
SF for KGai.

* Renamed a macro for clarity
* Rearranged the page navigation into PM navigation macro

**Comment by brianwulbern** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/688

**Comment by koor4356** [comment]
ci:retest

**Comment by brianwulbern** [comment]
SF for KGai.

* Split out "LRQA-17595 Use AssertElementPresent instead of AssertVisible" into two commits  (one for removing an excess macro call)
* Renamed the "userLanguageTranslation" macro block/call to be "changeUserLanguage", so it would fit the naming standard by starting with a verb.
* Fixed a typo

**Comment by brianwulbern** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/725

**Pull request closed without merging**
