### PR TITLE
[Draft PR] LPS-186127 Prohibiting single/double-word language keys without [context]

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Brian,
We have a first runnable check for your request.
Please check the test case to see if it can fit your requirement.

I added one new ant task `format-source-language-keys-context` to use the new SF check, it is for the current branch.

Also, here is the results when I ran it for `modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties`

```
     [java] java.lang.Exception: Found 30 formatting issues:
     [java] 1: The context '404' is invalid in the key 'http-status-code[404]': ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 2: The context '500' is invalid in the key 'http-status-code[500]': ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 3: The key for 'add-category' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 4: The key for 'add-child-category' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 5: The key for 'categories' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 6: The key for 'category' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 7: The key for 'checkout' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 8: The key for 'delete' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 9: The key for 'enabled' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 10: The key for 'flag' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 11: The key for 'history' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 12: The key for 'is-temporarily-unavailable' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 13: The key for 'log-exceptions-only-help' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 14: The key for 'map' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 15: The key for 'mapping' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 16: The key for 'monitoring-configuration-name' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 17: The key for 'object' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 18: The key for 'parent-category' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 19: The key for 'pending' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 20: The key for 'recent' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 21: The key for 'redirect-url' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 22: The key for 'second' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 23: The key for 'subcategories' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 24: The key for 'then' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 25: The key for 'timeout' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 26: The key for 'title' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 27: The key for 'view' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 28: The key for 'vote' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 29: The key for 'when' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)
     [java] 30: The key for 'workflow-status' should have the context in [] to indicate the specific meaning: ./modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties (SourceCheck:PropertiesLanguageKeysContextCheck)

```

### CODE REVIEW

**Comment by brianwulbern** [comment]
@ling-alan-huang @qz1010 
1. This looks great so far.  Single char contexts only allow `n` and `v`, and the disallow list looks good.
2. Are there only 30 results from the scan in the existing Language.properties file?  I feel like there could be hundreds...
3. `format.current.branch` doesn't run on the full `ant format-source`, correct?  If someone edits the Language.properties file, will the whole thing be scanned?
4. I think we need to allow http-status-code[404] and http-status-code[500], since those are URL status codes.
5. Are we currently flagging strings that have a multi-word key, but a single word value?  I think those can pass, because ones like: `is-temporarily-unavailable`, `log-exceptions-only-help`, `redirect-url`, and `workflow-status` carry enough context with them for meaning (`is-temporarily-unavailable` has another problem, but we can deal with that within each PT)

**Comment by ling-alan-huang** [comment]
> 1. This looks great so far. Single char contexts only allow n and v, and the disallow list looks good.
> 2. Are there only 30 results from the scan in the existing Language.properties file?  I feel like there could be hundreds...

Can you point which cases we missed?
are you referring those that key equals value?
Like:
```
theme=Theme
theme-colors=Theme Colors
theme-css=Theme CSS
```
 

> 3. `format.current.branch` doesn't run on the full `ant format-source`, correct?  If someone edits the Language.properties file, will the whole thing be scanned?

It is only for current branch, the changes in `Language.properties` must be in a commit in the current branch, then SF can scan it.

> 4. I think we need to allow http-status-code[404] and http-status-code[500], since those are URL status codes.

Okay, we probably need a whitelist includeing the keys like that.

> 5. Are we currently flagging strings that have a multi-word key, but a single word value?  I think those can pass, because ones like: `is-temporarily-unavailable`, `log-exceptions-only-help`, `redirect-url`, and `workflow-status` carry enough context with them for meaning (`is-temporarily-unavailable` has another problem, but we can deal with that within each PT)

I don't understand it, but now we don't check values, just check the keys.

**Comment by brianwulbern** [comment]
@ling-alan-huang 

> 2. are you referring those that key equals value?

Only when it's one for both key and value - so `theme=Theme` should get flagged.  One of the issues we have with single-word-key="word" is the lack of context we're trying to disallow.  Something like `order=Order` is a good case in point, as it could be a number of things.  However, as it looks like the scan did well in, something like `action.ACCESS=Access` or `action.ADD=Add` have enough context, so we can continue to not flag those.

> 5. I don't understand it, but now we don't check values, just check the keys.

Ok, I guess we just need to figure out why those keys are getting flagged, that's weird.

**Comment by brianwulbern** [comment]
@ling-alan-huang oh, a helpful toggle we could also benefit from is if we add a variable to the scan, call it `depth`.  Depth would associate to the number of words in a key.  So if I went into `/portal-impl` and ran:
```ant format-source-language-keys-context -Ddepth=2```

I could be searching for keys with two words in them (something like `actions-type`).  It might be a big ask, so I'll categorize it as a nice-to-have for now.

**Comment by ling-alan-huang** [comment]
Got it. @brianwulbern 
Btw, do you want to do scaning for whole portal source(or a specific dir) without any changes in your branch with that ant task?
I mean if there is no changes in your current branch, the task don't run for it.

Now, I think you want to run the check for a specific dir without changes, let me remove that ant task.
So, you can just run `ant format-source` as before, and with a parameter to enable this new SF check, and a parameter depth.

**Comment by brianwulbern** [comment]
@ling-alan-huang yeah, I'm ok with the ant task running in the normal `format-source` I just don't want it adding unnecessary noise before we can deal with the current keys

**Comment by ling-alan-huang** [comment]
@brianwulbern 
Sure, let me make some changes, so it would just like `ant format-source -Dbase.dir=xyz -Dsource.check=thisNewSFCheck -Ddepth=2`

**Comment by brianwulbern** [comment]
Nice, thanks!

**Comment by olafk** [comment]
Some comments on all of the above, undirected (and maybe long understood):

> Only when it's one for both key and value - so `theme=Theme` should get flagged

if I understand correctly, "one for both" would _always_ be true with Liferay's keys closely matching the english translation - so there's absolutely no need to take the value ("Theme") into account and only the key ("theme") should be enough to be flagged.

Examples for when Brian says "it can be a number of things" on "order": 
* the command to arrange entries in a certain way
* a noun used as a title to display the field entries are ordered by
* an order of stuff issued through Commerce

The disambiguation context can be anything, e.g. "[command]", "[noun,commerce]", "[404]" and - IMHO - doesn't need to be validated. It's arguable that it should have a certain length, but here I'd trust developers to provide something meaningful when they're pointed at a required translation context. After all, there's `git blame`.

And yes, there are _a lot_ more entries than 30, just for single word keys. What comes immediately to my mind is "open", which can be a command or a state (as in status). "view", and of course "from", "to" (time, location, sort-order-excerpt?) that started the whole idea on this SF. 

I'm happy to see this going on. In the short run it'll be a burden, in the long run it helps to dramatically improve translation (through policy as well as raised awareness)

**Comment by brianwulbern** [comment]
@olafk if you trust the developers to provide something meaningful - and if we start enforcing this, I'm sure BChan will also be happy to "wordsmith" and/or send things back for more clarity - then I think we can remove the validation check.  If things get out of hand, we may consider reinstating validation, but honestly, I also don't want to make it a game of cat-and-mouse.

@ling-alan-huang we can remove the validation on `[]` for now.

**Comment by ling-alan-huang** [comment]
@brianwulbern I decided to move the check out of SF(like what we did for `modules/util/lang-sanitizer`), just because it seems like an analysis kit. And if it's in SF, any violations against SF should be fixed.
Can you name this kit under modules/util?

**Comment by ling-alan-huang** [comment]
@qz1010 Can you continue this?

**Comment by brianwulbern** [comment]
@ling-alan-huang can we still move it into SF at a later time, in case we want to enforce it on pulls?

Hmm, short of having a 'real zinger' of a name, we can follow similar form as the lang-sanitizer and call the kit `modules/util/key-contextualizer` and run it with `ant contextualize-key`

**Comment by ling-alan-huang** [comment]
@brianwulbern Sure, but I am not sure how many violations will be, becasue I really don't want to add too many exclusions(language keys) in `source-formatter.properties`.

**Comment by brianwulbern** [comment]
@ling-alan-huang yep, totally agree - I intend to clean up the bad context keys first, then when the existing ones are taken care of, it'll be safe to turn on with the main SF check (pending any necessary approvals from stakeholders).

**Comment by ling-alan-huang** [comment]
Got it, let's make the rule in SF and disable it for now.

**Comment by ling-alan-huang** [comment]
BChan owns 'approval' for any SF.

**Comment by ling-alan-huang** [comment]
@brianwulbern see https://github.com/brianwulbern/liferay-portal/pull/427

**Pull request closed without merging**
