### PR TITLE
LPS-58504 New portlet decorators

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianwulbern** [comment]
@epgarcia Still working on this one, sorry.  It broke the Smoke test on a handful of locators.  Will have a fix tomorrow.

**Comment by epgarcia** [comment]
NP. If you have any questions, please contact me or @marcoscv-work 
Thanks!

**Comment by brianwulbern** [comment]
@epgarcia @marcoscv-work 

I'm seeing this error a lot when refreshing a page: `ReferenceError: LiferayAUI is not defined`

And this one, iteratively, after clicking into another page and hovering over any link element: `TypeError: Liferay.Navigation is not a constructor` - ad infinitum, as long as you're hovering over a link.

I think I can still get the test to work, but there will be a boatload of JavaScript warnings thrown in the smoke test browser.

**Comment by epgarcia** [comment]
@marcoscv-work Can you have a look at it?

**Comment by brianwulbern** [comment]
@epgarcia @marcoscv-work 

Ok, I've got the fixes ready.  I've pushed this to @brianchiu here: https://github.com/brianchiu/liferay-portal/pull/776.

I'm still getting the JavaScript errors, but the Smoke test completes successfully.  We'll see what outside of the Smoke test errors out in my pull.  I don't know if you want to push fixes for the JavaScript errors to me, or just push them separately from these commits you already have.  Let me know if you want to push them on this PR, and I'll reopen it.

Thanks!

**Comment by marcoscv-work** [comment]
Hey guys, I have been looking for these errors but I have not been able to find them. I think it is not from this pull and we could go ahead.

Anyway, @brianwulbern , Could you give me any indications about how to find these errors?

**Comment by brianwulbern** [comment]
Hi @marcoscv-work @epgarcia 

I added a gif of how I reproduced the JavaScript errors to the LPS ticket: https://issues.liferay.com/browse/LPS-58504

**Comment by marcoscv-work** [comment]
Hi @brianwulbern I've been testing the last @epgarcia commits and I don't have these errors, Have you tested this before your commits?

noerrors

**Comment by brianwulbern** [comment]
Hi @marcoscv-work @epgarcia

I was able to reproduce the JS errors from the start, and on through my commits (but not at master head).  If neither of you are seeing those errors, then it must be a configuration thing on my end.  And we won't have to worry about it.  Thanks!

**Pull request closed without merging**
