### PR TITLE
LRQA-29308, LRQA-29761, LRQA-29822, LRQA-29848 | 7.0.x

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-29308
https://issues.liferay.com/browse/LRQA-29761
https://issues.liferay.com/browse/LRQA-29822
https://issues.liferay.com/browse/LRQA-29848

### CODE REVIEW

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed LRQA-29761 and LRQA-29822 to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45773
https://github.com/brianchandotcom/liferay-portal/pull/45774

**Comment by brianwulbern** [comment]
See https://issues.liferay.com/browse/LRQA-29848 for more information.  It will be covered on https://issues.liferay.com/browse/LRQA-29870

@liuxingye

**Comment by brianwulbern** [comment]
Working on LRQA-29308...

**Comment by liuxingye** [comment]
@brianwulbern Got it, thanks

**Comment by brianwulbern** [comment]
SF for @GinsonRen @Sharryxue 
* Made the while-loop only run when ${themeSite} is set to true.

**Comment by brianwulbern** [comment]
Pushed LRQA-29308 to AChu.
https://github.com/anthony-chu/liferay-portal/pull/95

**Pull request closed without merging**
