### PR TITLE
7.0.x-qa-30159

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-30159
@GinsonRen

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:retest

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:retest

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to ALee.
7.0.x: https://github.com/alee8888/liferay-portal/pull/439
master: https://github.com/alee8888/liferay-portal/pull/440

**Pull request closed without merging**
