### PR TITLE
master-qa-26156

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26156

### CODE REVIEW

**Comment by anthony-chu** [comment]
Test failure does not appear to be related to test fixes.

**Comment by brianwulbern** [comment]
@anthony-chu Since you know the upgrades tests, can you tell if that's a flaky failure that can be fixed?

**Comment by brianwulbern** [comment]
No test changes needed.  Nice job with the new toggle macro. :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40989
https://github.com/brianchandotcom/liferay-portal/pull/40990

**Pull request closed without merging**
