### PR TITLE
master-qa-71981

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-71981
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@chaowang-123 please resend this using a more specific name, like `CanExportUsersWithDirectServletContextDisabled`

**Comment by brianwulbern** [comment]
Maybe you can ask me about the test name you'd suggest, then after we settled on a good name, you can write the test 👍

**Comment by chaowang-123** [comment]
> Maybe you can ask me about the test name you'd suggest, then after we settled on a good name, you can write the test

got it, thanks!

**Comment by brianwulbern** [comment]
@chaowang-123 it looks like after your change the test now should go after the one below it `CanBulkActivateUsers`

**Pull request closed without merging**
