### PR TITLE
master-qa-71986

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-71986
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
ci:forward

**Pull request closed without merging**
