### PR TITLE
master-qa-26186

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-26186

### CODE REVIEW

**Comment by brianwulbern** [comment]
should we make the build-test logic for this one, too, or did you just want to start the labeling?

**Comment by anthony-chu** [comment]
@brianwulbern Per our conversation, this property can be used by jenkins to select a subset of content targeting tests that pertain to a particular release; this will allow us to add new tests without having to run them during a release cycle.

**Comment by brianwulbern** [comment]
No test changes needed :)

**Comment by brianwulbern** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41021
https://github.com/brianchandotcom/liferay-portal/pull/41022

**Pull request closed without merging**
